### PR TITLE
Added Poison Study by Maria V Snyder

### PR DESCRIPTION
**Pull request by louisefindlay23**
Added Poison Study by Maria V Snyder to the Standard Fantasy section.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thanks! I think all of the descriptions should be quoted; can you fix that?

**Comment by RichardLitt** [comment]
I'm sorry. I did not mean add quotes to all of the descriptions. I meant that your original entry was not in the appropriate format, using:

```markdown
This format, where

> This is in a quote block
```

Instead, there was no quote block for your entry. Make sense.

**Comment by louisefindlay23** [comment]
I've just reverted that commit and added the quote block to the book's description. Thanks for clarifying.

**Comment by RichardLitt** [comment]
Excellent! Thank you for this addition. Sorry about the confusion. :)

**Pull request merged**
