### PR TITLE
Corrected misspelt word added new tv show

### PR DESCRIPTION
**Pull request by gayatripalkar**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thank you! Could you squash these commits?

**Comment by RichardLitt** [comment]
Got it. Thank you!

**Comment by gayatripalkar** [comment]
> Thank you! Could you squash these commits?

I am brand new to Open Source and Don't know how to do that, can you guide me?

**Comment by RichardLitt** [comment]
Don't worry about it - I temporarily forgot that GitHub squashes commits for me. You're all set. For more, look at https://github.com/k88hudson/git-flight-rules.

**Pull request merged**
