### PR TITLE
Add the belgariad

### PR DESCRIPTION
**Pull request by codercarly**

### CODE REVIEW

**Comment by RichardLitt** [comment]
The Belgeriad seems cool, but could you please remove all of the other changes in this file?

**Comment by codercarly** [comment]
Sorry about that, I'm not at all sure how that happened. I only added the one section, not sure why it would show that I made changes to all the other sections. Very strange.

**Comment by RichardLitt** [comment]
Were you using a local IDE? It's possible it automatically formatted the Markdown for you. 

Try adding this using the Web interface, or learn about using `git add -p` and amending the commit.

**Comment by codercarly** [comment]
I'm using Visual Studio Code. I installed GitLens and yeah, I think it reformatted the markdown. I'll see about amending the commit, if not I'll add the information through the web interface.

**Comment by RichardLitt** [comment]
Thanks. Feel free to open a new PR if that is easier.

**Comment by codercarly** [comment]
Thanks! I appreciate it! Gotta let the masses know about the Belgariad!

**Pull request closed without merging**
