### PR TITLE
The Colour of Magic added

### PR DESCRIPTION
**Pull request by fourlastor**
This pull requests adds "The Colour of Magic" by Terry Pratchett to the list, first of the Discworld serie.

I read the first 9 books and currently reading the book 10, suggestions on how to improve are welcome :)

### CODE REVIEW

**Comment by RichardLitt** [comment]
Hey! Thanks! This looks great; maybe having a discworld section would be good, but for now this works as they are kind of all stand-alone. Could you add a commentary about why you think it is awesome, though? I've been trying to do that for all of the books here.

**Comment by fourlastor** [comment]
Sure I will, tomorrow I'm going to fix this then :)

**Comment by RichardLitt** [comment]
Awesome.

**Comment by fourlastor** [comment]
ok, just added the commentary after the small introduction to Discworld :)

**Comment by RichardLitt** [comment]
Looks great! thanks man. :)

**Pull request merged**
