### PR TITLE
Added The Magicians tv show entry.

### PR DESCRIPTION
**Pull request by Chad-Ballay**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thanks. Can you alphabetize this?

**Comment by RichardLitt** [comment]
I'm going to reconsider adding this once I've read the books. Thanks.

**Comment by Mikaela** [comment]
Who is the author of the books or how can I find them?

**Comment by Chad-Ballay** [comment]
https://en.m.wikipedia.org/wiki/The_Magicians_(Grossman_novel)

It’s also the basis for a tv series but the plot deviates from the book significantly. Not in a bad way, it’s very good still.

**Pull request closed without merging**
