### PR TITLE
New Humor Book. Cuentos de Humor y Sátira de Edgar Alllan Poe

### PR DESCRIPTION
**Pull request by Iker1211**
This book is little known because of his author. A lot time ago I read it and was one of the first impressions I had of him. I really like the style and the ocurrences. Later I discoverded Edgar Allan Poe has more books of other different topics.

### CODE REVIEW

**Comment by RichardLitt** [comment]
You appear to have also added a GitHub Actions workflow?

**Comment by M120-gift** [comment]
Yes

**Comment by M120-gift** [comment]
Thanks

**Comment by RichardLitt** [comment]
I could have been clearer. Happy to merge the PR if you remove the GitHub Actions workflow, @Iker1211.

**Pull request closed without merging**
