### PR TITLE
Alphabetized all the titles

### PR DESCRIPTION
**Pull request by Charpal**
Hi! I just put all the titles in alphabetical order. Let me know if something's wrong. Thanks!

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thanks?

**Comment by RichardLitt** [comment]
Looks like there are conflicts. Can you resolve those?

**Comment by Charpal** [comment]
Done.

**Comment by RichardLitt** [comment]
I am just going to assume that this is done correctly and that you didn't split in a copy of Sailor Moon or something.

**Comment by RichardLitt** [comment]
Thanks.

**Pull request merged**
