### PR TITLE
Add the Rythm of War to The Stormlight Archive and add some fires

### PR DESCRIPTION
**Pull request by ExtinctAxolotl**
Add the Rythm of War to The Stormlight Archive by Brandon Sanderson and add the fire emojis to Oathbringer and Words of Radiance (all in the Stormlight Archive Series)

### CODE REVIEW

**Comment by RichardLitt** [comment]
Looks good to me! I've read this, but would you be interested in adding a blurb as to why they belong here? Why are they awesome, for you?

**Comment by ExtinctAxolotl** [comment]
I'm Sorry. I somehow missed the part of needing to read the books, when suggesting them (Don't ask me how). Sorry for wasting your time on this.

**Comment by RichardLitt** [comment]
It's alright! Still worth having. As I've said, I've read them, and while I don't personally think they are awesome, I know close friends people who do.

Could you spell Rhythm correctly, and then we can merge this?

**Review by RichardLitt — COMMENTED** [review]
Rythm should be Rhythm.

**Comment by RichardLitt** [comment]
Nevermind, got it. Merged!

**Comment by ExtinctAxolotl** [comment]
Thank you Richard for your patience!
I Truly appreciate it!

**Pull request merged**
