### PR TITLE
Added T.V. Show Mr. Sunshine to README.md file

### PR DESCRIPTION
**Pull request by Lauren2590**
Here is my contribution.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thanks! This is not in the right place, however. I don't think this is fantasy - do you?

**Comment by Lauren2590** [comment]
Ohh I’m sorry...

**Comment by Lauren2590** [comment]
Is it too late to add something else to this repository?

**Comment by RichardLitt** [comment]
It's never too late. You can always open another PR. :)

**Comment by Lauren2590** [comment]
Okay, thanks. :)

**Pull request closed without merging**
